/**
 * Dropster 1.4
 *
 * Dropster abstracts and simplifies drag and
 * drop and enables file uploads with AJAX.
 *
 * @version 1.4.2
 * @author Ardalan Samimi
 */
 (function(c){var h=function(b,a){this.element=c(b);this.inputFile=!1;this.settings=c.extend({url:!1,auto:!0,uploadLimit:0,loaderImagePath:"/node_modules/dropster/lib/loading-128.png",extensions:["jpg","jpeg","gif","png"],monitor:!1,onDownload:function(b){},onUpload:function(b){},onChange:function(b,a){},onReady:function(b){},onError:function(b){}},a||{});this.onInit();this.bindDragEvents()};h.prototype={onInit:function(){this.setPublicInterface();console.log(this.publicInterface);!0===this.settings.auto&&
this.setAutoUpload()},onDownload:function(b){b=Math.round(++this.publicInterface.totalSizeLoaded/this.publicInterface.totalSizeToLoad*1E3/10);this.onProgress("Uploading files... "+b+"%")},onUpload:function(b){var a=0;b.lengthComputable&&(a=Math.round(b.loaded/b.total*1E3/10));this.onProgress("Uploading files... "+a+"%")},onChange:function(b,a){if(4===b&&404===a)this.onError("Error code "+a)},onReady:function(b){this.resetFileInput();1>c("#dropster-window").length&&this.createWindow(!1);b=c(".dropster-window-header");
var a=c(".dropster-window-body");b.html("Upload finish!");a.children().remove();a.html("The files have been successfully uploaded.")},onError:function(b){1>c("#dropster-window").length&&this.createWindow(!1);var a=c(".dropster-window-header"),d=c(".dropster-window-body");a.html("Upload error");d.children().remove();d.html("An error has occurred: "+b)},setPublicInterface:function(){var b=new RegExp(/(\{\s\})|(\{\})/),a={};for(method in this.settings)if(c.isFunction(this.settings[method]))if(b.test(this.settings[method].toString()))c.isFunction(this[method])&&
(a[method]=this[method].bind(this));else{var d=this.createDefaultMethodName(method);a[method]=this.settings[method];a[d]=this[method].bind(this)}this.publicInterface=a;this.publicInterface.monitor=this.settings.monitor;this.publicInterface.totalSizeToLoad=0;this.publicInterface.totalSizeLoaded=0},setAutoUpload:function(){var b=this.element.find("input[type='file']");if(0<b.length){var a=this;this.inputFile=b;this.publicInterface.resetFileInput=this.resetFileInput.bind(this);this.inputFile.on("change",
function(b){a.onDrop(b,!0,!1)})}},bindDragEvents:function(){var b=this,a=this.element;a.on("dragenter",function(d){b.dragEnter(d,a)});a.on("dragover",function(a){b.dragOver(a)});a.on("drop",function(d){b.drop(d,a)});a.on("dragleave",function(a){b.dragLeave(a)});c(document).on("dragenter",function(a){b.dragEnter(a)});c(document).on("drop",function(a){b.drop(a)});c(document).on("dragover",function(d){b.dragOver(d,a)})},dragEnter:function(b,a){c(".dropster-highlight").removeClass("dropster-highlight");
a=a||!1;!1!==a&&a.addClass("dropster-highlight");this.onDrop(b)},dragOver:function(b,a){a=a||!1;!1!==a&&a.removeClass("dropster-highlight");this.onDrop(b)},dragLeave:function(b,a){a=a||!1;!1!==a&&a.removeClass("dropster-highlight");this.dragOver(b)},drop:function(b,a){a=a||!1;var d=!1,c=!1;!1!==a&&(a.removeClass("dropster-highlight"),c=d=!0);this.onDrop(b,d,c)},onDrop:function(b,a,d){a=a||!1;d=d||!1;b.stopPropagation();b.preventDefault();if(!0===a){b=1==d?b.originalEvent.dataTransfer.files:b.currentTarget.files;
var e=new FormData,f=!1,g=this;c.each(b,function(b,a){if(!1===g.checkExtension(a.name))return g.publicInterface.onError("Could not upload file "+a.name+". File extension not allowed."),f=!0,!1;e.append("file"+b,a);if(0!==g.settings.uploadLimit&&g.settings.uploadLimit==b+1)return!1});if(f)return!1;this.sendDrop(e,b.length)}},sendDrop:function(b,a){b=b||!1;a=a||!1;if(!1===b||!1===a)return!1;var d=this,c=new XMLHttpRequest;d.publicInterface.totalSizeToLoad=a;c.upload.onprogress=function(a){d.publicInterface.onUpload(a)};
c.onprogress=function(a){d.publicInterface.onDownload(a)};c.onreadystatechange=function(){if(4===c.readyState&&200===c.status)console.log(c.readyState),console.log(c.responseText),d.publicInterface.onReady(c.responseText);else d.publicInterface.onChange(c.readyState,c.status,c.responseText)};if(!1!==d.settings.url)c.open("POST",d.settings.url),c.setRequestHeader("X-Requested-With","XMLHttpRequest"),c.send(b);else d.publicInterface.onError("No upload path set")},checkExtension:function(b){extension=
b.split(".").pop().toLowerCase();return-1!=c.inArray(extension,this.settings.extensions)?!0:!1},createDefaultMethodName:function(b){return/[A-Z]/.test(b.charAt(0))?"default"+b:"default"+b.charAt(0).toUpperCase()+b.substring(1)},createWindow:function(b){b=b||!1;var a=c("<div>"),d=a.clone().attr({id:"dropster-window"});a.clone().attr({"class":"dropster-window-header"}).appendTo(d);var e=a.clone().attr({"class":"dropster-window-body"}).appendTo(d),f=a.clone().attr({"class":"dropster-window-footer"}).appendTo(d);
a.clone().attr({"class":"dropster-window-button"}).html("OK").appendTo(f).on("click",function(){c("#dropster-window").remove()});b&&c("<img>").attr({src:this.settings.loaderImagePath}).appendTo(e);d.appendTo("body")},onProgress:function(b){1>c("#dropster-window").length&&this.createWindow(!0);c(".dropster-window-header").html(b)},resetFileInput:function(){!1!==this.inputFile&&this.inputFile.val("")},updateSettings:function(b){this.settings=c.extend(this.settings,b);this.onInit()}};c.fn.dropster=function(b){return this.each(function(){var a=
c(this).data("plugin_dropster");a?a.updateSettings(b):c(this).data("plugin_dropster",new h(this,b))})}})(jQuery);
