/**
 * Dropster 1.5
 *
 * Dropster abstracts and simplifies drag and
 * drop and enables file uploads with AJAX.
 *
 * @version 1.5.1
 * @author Ardalan Samimi
 */
 (function(){window.jQuery&&($.fn.dropster=function(a){return this.each(function(){var b=$(this).data("plugin_dropster");b?b.updateSettings(a):$(this).data("plugin_dropster",new e(this,a))})});Element.prototype.dropster=function(a){return new e(this,a)};var g={url:!1,auto:!0,createArea:!1,uploadLimit:0,loaderImagePath:"/node_modules/dropster/lib/loading-128.png",extensions:["jpg","jpeg","gif","png"],monitor:!1,onDownload:function(a){},onUpload:function(a){},onChange:function(a,b){},onReady:function(a){},
onError:function(a){}},e=function(a,b){this.element=a;this.inputFile=!1;this.settings=this.extend(b,g);this.globals={highlightClassName:"dropster-highlight"};!0===this.settings.createArea&&this.createDropArea();this.setPublicInterface();!0===this.settings.auto&&this.setAutoUpload();this.on(this.element,"dragenter",this.dragEnter.bind(this));this.on(this.element,"dragleave",this.dragLeave.bind(this));this.on(this.element,"dragover",this.dragLeave.bind(this));this.on(this.element,"drop",this.drop.bind(this));
this.on(document,"dragenter",this.dragEnter.bind(this));this.on(document,"dragover",this.dragLeave.bind(this));this.on(document,"drop",this.drop.bind(this))};e.prototype={on:function(a,b,c){a.addEventListener(b,function(b){c(b,a)},!1)},dragEnter:function(a,b){b=b||!1;b===this.element&&!1===b.classList.contains(this.globals.highlightClassName)&&b.classList.add(this.globals.highlightClassName);this.onDrop(a)},dragLeave:function(a,b){(b||!1)!==this.element&&!0===this.element.classList.contains(this.globals.highlightClassName)&&
this.element.classList.remove(this.globals.highlightClassName);this.onDrop(a)},drop:function(a,b){b=b||!1;if(b===this.element)b.classList.remove(this.globals.highlightClassName),this.onDrop(a,!0,!0);else this.onDrop(a,!1,!1)},onDrop:function(a,b,c){b=b||!1;c=c||!1;a.stopPropagation();a.preventDefault();if(!0===b){a=c?a.dataTransfer.files:a.currentTarget.files;b=new FormData;for(c=0;c<a.length;c++){if(!1===this.checkExtension(a[c].name))return this.publicInterface.onError("Could not upload file "+
a[c].name+". File extension not allowed."),!1;b.append("file_"+c,a[c]);if(0!==this.settings.uploadLimit&&this.settings.uploadLimit===c+1)break}this.sendDrop(b,a.length)}},sendDrop:function(a,b){a=a||!1;b=b||!1;if(!1===a||!1===b)return!1;var c=this,d=new XMLHttpRequest;c.publicInterface.totalSizeToLoad=b;d.upload.onprogress=function(a){c.publicInterface.onUpload(a)};d.onprogress=function(a){c.publicInterface.onDownload(a)};d.onreadystatechange=function(){if(4===d.readyState&&200===d.status)c.publicInterface.onReady(d.responseText);
else c.publicInterface.onChange(d.readyState,d.status)};if(!1!==c.settings.url)d.open("POST",c.settings.url),d.setRequestHeader("X-Requested-With","XMLHttpRequest"),d.send(a);else c.publicInterface.onError("No upload path set")},setPublicInterface:function(){var a=new RegExp(/(\{\s\})|(\{\})/),b={};for(method in this.settings)if("function"===typeof this.settings[method]&&"function"===typeof this[method])if(a.test(this.settings[method].toString()))b[method]=this[method].bind(this);else{var c=this.createDefaultMethodName(method);
b[method]=this.settings[method];b[c]=this[method].bind(this)}this.publicInterface=b;this.publicInterface.monitor=this.settings.monitor;this.publicInterface.totalSizeToLoad=0;this.publicInterface.totalSizeLoaded=0},setAutoUpload:function(){var a=this.element.querySelectorAll("input[type=file]")[0];if(null!==a&&"undefined"!==typeof a){var b=this;this.inputFile=a;this.publicInterface.resetFileInput=this.resetFileInput.bind(this);this.on(this.inputFile,"change",function(a){b.onDrop(a,!0,!1)})}},extend:function(a,
b){for(var c in b)!1===a.hasOwnProperty(c)&&(a[c]=b[c]);return a},createDefaultMethodName:function(a){return/[A-Z]/.test(a.charAt(0))?"default"+a:"default"+a.charAt(0).toUpperCase()+a.substring(1)},checkExtension:function(a){extension=a.split(".").pop().toLowerCase();return-1!==this.settings.extensions.indexOf(extension)?!0:!1},onProgress:function(a){var b=document.getElementById("dropster-window");null===b&&(b=this.createWindow(!0));divHeader=b.getElementsByClassName("dropster-window-header")[0];
divHeader.innerHTML=a},onDownload:function(a){a=Math.round(++this.publicInterface.totalSizeLoaded/this.publicInterface.totalSizeToLoad*1E3/10);this.onProgress("Uploading files... "+a+"%")},onUpload:function(a){var b=0;a.lengthComputable&&(b=Math.round(a.loaded/a.total*1E3/10));this.onProgress("Uploading files... "+b+"%")},onChange:function(a,b){if(4===a&&404===b)this.onError("Error code "+b)},onReady:function(a){this.resetFileInput();var b=document.getElementById("dropster-window");null===b&&(b=this.createWindow(!1));
a=b.getElementsByClassName("dropster-window-header")[0];b=b.getElementsByClassName("dropster-window-body")[0];for(a.innerHTML="Upload finish!";b.lastChild;)b.removeChild(b.lastChild);b.innerHTML="The files have been successfully uploaded."},onError:function(a){var b=document.getElementById("dropster-window");null===b&&(b=this.createWindow(!1));var c=b.getElementsByClassName("dropster-window-header")[0],b=b.getElementsByClassName("dropster-window-body")[0];for(c.innerHTML="Upload error!";b.lastChild;)b.removeChild(b.lastChild);
b.innerHTML="An error has occurred: "+a},cloneElement:function(a,b,c){c=c||null;a=a.cloneNode(!1);for(var d in b)a.setAttribute(d,b[d]);null!==c&&(a.innerHTML=c);return a},createDropArea:function(){var a=document.createElement("p"),b=this.cloneElement(a,{},"Drag and drop files here or use the browse button below"),a=this.cloneElement(a,{}),c=this.cloneElement(document.createElement("input"),{type:"file"});a.appendChild(c);this.element.appendChild(b);this.element.appendChild(a);this.element.classList.add("dropster-target-area")},
createWindow:function(a){a=a||!1;var b=document.createElement("div"),c=this.cloneElement(b,{id:"dropster-window"}),d=this.cloneElement(b,{"class":"dropster-window-header"}),e=this.cloneElement(b,{"class":"dropster-window-body"}),f=this.cloneElement(b,{"class":"dropster-window-footer"}),b=this.cloneElement(b,{"class":"dropster-window-button"},"OK");c.appendChild(d);c.appendChild(e);c.appendChild(f);f.appendChild(b);b.addEventListener("click",function(){c.parentNode.removeChild(c)});a&&(a=document.createElement("img"),
a.src=this.settings.loaderImagePath,e.appendChild(a));document.body.appendChild(c);return c},resetFileInput:function(){!1!==this.inputFile&&(this.inputFile.value="")}}})();
