/**
 * Javascript plugin
 * Dropster 1.3.1
 *
 * Dropster abstracts and simplifies drag and
 * drop and enables file uploads with AJAX.
 *
 * @version 1.3.1
 * @author Ardalan Samimi
 */
 (function(c){var h=function(a,b){this.element=c(a);this.inputFile=!1;this.settings=c.extend({url:!1,auto:!0,uploadLimit:0,loaderImagePath:"/node_modules/dropster/lib/loading-128.png",extensions:["jpg","jpeg","gif","png"],monitor:!1,onDownload:function(a){},onUpload:function(a){},onReady:function(a){},onError:function(a){}},b||{});this.setPublicInterface();this.bindDragEvents();!0===this.settings.auto&&this.setAutoUpload()};h.prototype={onDownload:function(a){a=Math.round(++this.publicInterface.totalSizeLoaded/
this.publicInterface.totalSizeToLoad*1E3/10);this.onProgress("Uploading files... "+a+"%")},onUpload:function(a){var b=0;a.lengthComputable&&(b=Math.round(a.loaded/a.total*1E3/10));this.onProgress("Uploading files... "+b+"%")},onReady:function(a){this.resetFileInput();1>c("#dropster-window").length&&this.createWindow(!1);a=c(".dropster-window-header");var b=c(".dropster-window-body");a.html("Upload finish!");b.children().remove();b.html("The files have been successfully uploaded.")},onError:function(a){1>
c("#dropster-window").length&&this.createWindow(!1);var b=c(".dropster-window-header"),d=c(".dropster-window-body");b.html("Upload error");d.children().remove();d.html("An error has occurred: "+a)},setPublicInterface:function(){var a=new RegExp(/(\{\s\})|(\{\})/),b={};for(method in this.settings)if(c.isFunction(this.settings[method]))if(a.test(this.settings[method].toString()))c.isFunction(this[method])&&(b[method]=this[method].bind(this));else{var d=this.createDefaultMethodName(method);b[method]=
this.settings[method];b[d]=this[method].bind(this)}this.publicInterface=b;this.publicInterface.monitor=this.settings.monitor;this.publicInterface.totalSizeToLoad=0;this.publicInterface.totalSizeLoaded=0},setAutoUpload:function(){var a=this.element.find("input[type='file']");if(0<a.length){var b=this;this.inputFile=a;this.publicInterface.resetFileInput=this.resetFileInput.bind(this);this.inputFile.on("change",function(a){b.onDrop(a,!0,!1)})}},bindDragEvents:function(){var a=this,b=this.element;b.on("dragenter",
function(d){a.dragEnter(d,b)});b.on("dragover",function(b){a.dragOver(b)});b.on("drop",function(d){a.drop(d,b)});b.on("dragleave",function(b){a.dragLeave(b)});c(document).on("dragenter",function(b){a.dragEnter(b)});c(document).on("drop",function(b){a.drop(b)});c(document).on("dragover",function(d){a.dragOver(d,b)})},dragEnter:function(a,b){c(".dropster-highlight").removeClass("dropster-highlight");b=b||!1;!1!==b&&b.addClass("dropster-highlight");this.onDrop(a)},dragOver:function(a,b){b=b||!1;!1!==
b&&b.removeClass("dropster-highlight");this.onDrop(a)},dragLeave:function(a,b){b=b||!1;!1!==b&&b.removeClass("dropster-highlight");this.dragOver(a)},drop:function(a,b){b=b||!1;var d=!1;!1!==b&&(b.removeClass("dropster-highlight"),d=!0);this.onDrop(a,d,!1)},onDrop:function(a,b,d){b=b||!1;d=d||!1;a.stopPropagation();a.preventDefault();if(!0===b){a=!0===d?a.originalEvent.dataTransfer.files:a.currentTarget.files;var e=new FormData,f=!1,g=this;c.each(a,function(a,b){if(!1===g.checkExtension(b.name))return g.publicInterface.onError("Could not upload file "+
b.name+". File extension not allowed."),f=!0,!1;e.append("file"+a,b);if(0!==g.settings.uploadLimit&&g.settings.uploadLimit==a+1)return!1});if(f)return!1;this.sendDrop(e,a.length)}},sendDrop:function(a,b){a=a||!1;b=b||!1;if(!1===a||!1===b)return!1;var d=this,c=new XMLHttpRequest;d.publicInterface.totalSizeToLoad=b;c.upload.onprogress=function(a){d.publicInterface.onUpload(a)};c.onprogress=function(a){d.publicInterface.onDownload(a)};c.onreadystatechange=function(){if(4===c.readyState)d.publicInterface.onReady(c.responseText)};
if(!1!==d.settings.url)c.open("POST",d.settings.url),c.setRequestHeader("X-Requested-With","XMLHttpRequest"),c.send(a);else d.publicInterface.onError("No upload path set")},checkExtension:function(a){extension=a.split(".").pop().toLowerCase();return-1!=c.inArray(extension,this.settings.extensions)?!0:!1},createDefaultMethodName:function(a){return/[A-Z]/.test(a.charAt(0))?"default"+a:"default"+a.charAt(0).toUpperCase()+a.substring(1)},createWindow:function(a){a=a||!1;var b=c("<div>"),d=b.clone().attr({id:"dropster-window"});
b.clone().attr({"class":"dropster-window-header"}).appendTo(d);var e=b.clone().attr({"class":"dropster-window-body"}).appendTo(d),f=b.clone().attr({"class":"dropster-window-footer"}).appendTo(d);b.clone().attr({"class":"dropster-window-button"}).html("OK").appendTo(f).on("click",function(){c("#dropster-window").remove()});a&&c("<img>").attr({src:this.settings.loaderImagePath}).appendTo(e);d.appendTo("body")},onProgress:function(a){1>c("#dropster-window").length&&this.createWindow(!0);c(".dropster-window-header").html(a)},
resetFileInput:function(){!1!==this.inputFile&&this.inputFile.val("")}};c.fn.dropster=function(a){return this.each(function(){c(this).data("plugin_dropster")||c(this).data("plugin_dropster",new h(this,a))})}})(jQuery);
