/**
 * Javascript plugin
 * Dropster 1.2
 *
 * Adds drag and drop functionality to an HTML element,
 * and uploading files to the server.
 *
 * @version 1.2
 * @author Ardalan Samimi
 */
 (function(c){var h=function(b,a){this.element=c(b);this.settings=c.extend({url:!1,uploadLimit:0,loaderImagePath:"/node_modules/dropster/lib/loading-128.png",extensions:["jpg","jpeg","gif","png"],monitor:!1,onDownload:function(a){},onUpload:function(a){},onReady:function(a){},onError:function(a){}},a||{});this.setPublicInterface();this.bindDragEvents()};h.prototype={onDownload:function(b){b=Math.round(++this.publicInterface.totalSizeLoaded/this.publicInterface.totalSizeToLoad*1E3/10);this.onProgress("Uploading files... "+
b+"%")},onUpload:function(b){var a=0;b.lengthComputable&&(a=Math.round(b.loaded/b.total*1E3/10));this.onProgress("Uploading files... "+a+"%")},onReady:function(b){1>c("#dropster-window").length&&this.createWindow(!1);b=c(".dropster-window-header");var a=c(".dropster-window-body");b.html("Upload finish!");a.children().remove();a.html("The images have been successfully uploaded.")},onError:function(b){1>c("#dropster-window").length&&this.createWindow(!1);var a=c(".dropster-window-header"),d=c(".dropster-window-body");
a.html("Upload error");d.children().remove();d.html("An error has occurred: "+b)},setPublicInterface:function(){var b=new RegExp(/(\{\s\})|(\{\})/),a={};for(method in this.settings)if(c.isFunction(this.settings[method]))if(b.test(this.settings[method].toString()))c.isFunction(this[method])&&(a[method]=this[method].bind(this));else{var d=this.createDefaultMethodName(method);a[method]=this.settings[method];a[d]=this[method].bind(this)}this.publicInterface=a;this.publicInterface.monitor=this.settings.monitor;
this.publicInterface.totalSizeToLoad=0;this.publicInterface.totalSizeLoaded=0},bindDragEvents:function(){var b=this,a=this.element;a.on("dragenter",function(d){b.dragEnter(d,a)});a.on("dragover",function(a){b.dragOver(a)});a.on("drop",function(d){b.drop(d,a)});a.on("dragleave",function(a){b.dragLeave(a)});c(document).on("dragenter",function(a){b.dragEnter(a)});c(document).on("drop",function(a){b.drop(a)});c(document).on("dragover",function(d){b.dragOver(d,a)})},dragEnter:function(b,a){c(".dropster-highlight").removeClass("dropster-highlight");
a=a||!1;!1!==a&&a.addClass("dropster-highlight");this.onDrop(b)},dragOver:function(b,a){a=a||!1;!1!==a&&a.removeClass("dropster-highlight");this.onDrop(b)},dragLeave:function(b,a){a=a||!1;!1!==a&&a.removeClass("dropster-highlight");this.dragOver(b)},drop:function(b,a){a=a||!1;var d=!1;!1!==a&&(a.removeClass("dropster-highlight"),d=!0);this.onDrop(b,d)},onDrop:function(b,a){a=a||!1;b.stopPropagation();b.preventDefault();if(!0===a){var d=b.originalEvent.dataTransfer.files,f=new FormData,g=!1,e=this;
c.each(d,function(a,b){if(!1===e.checkExtension(b.name)){var d=e.getSetting("onError");if(!1===d)e.onError("Could not upload file "+b.name+". File extension not allowed.");else d("Could not upload file "+b.name+". File extension not allowed.");g=!0;return!1}f.append("file"+a,b);if(0!==e.settings.uploadLimit&&e.settings.uploadLimit==a+1)return!1});if(g)return!1;this.sendDrop(f,d.length)}},sendDrop:function(b,a){b=b||!1;a=a||!1;if(!1===b||!1===a)return!1;var d=this,c=new XMLHttpRequest;d.publicInterface.totalSizeToLoad=
a;c.upload.onprogress=function(a){d.publicInterface.onUpload(a)};c.onprogress=function(a){d.publicInterface.onDownload(a)};c.onreadystatechange=function(){if(4===c.readyState)d.publicInterface.onReady(c.responseText)};if(!1!==d.settings.url)c.open("POST",d.settings.url),c.setRequestHeader("X-Requested-With","XMLHttpRequest"),c.send(b);else d.publicInterface.onError("No upload path set")},checkExtension:function(b){extension=b.split(".").pop().toLowerCase();return-1!=c.inArray(extension,this.settings.extensions)?
!0:!1},createDefaultMethodName:function(b){return/[A-Z]/.test(b.charAt(0))?"default"+b:"default"+b.charAt(0).toUpperCase()+b.substring(1)},createWindow:function(b){b=b||!1;var a=c("<div>"),d=a.clone().attr({id:"dropster-window"});a.clone().attr({"class":"dropster-window-header"}).appendTo(d);var f=a.clone().attr({"class":"dropster-window-body"}).appendTo(d),g=a.clone().attr({"class":"dropster-window-footer"}).appendTo(d);a.clone().attr({"class":"dropster-window-button"}).html("OK").appendTo(g).on("click",
function(){c("#dropster-window").remove()});b&&c("<img>").attr({src:this.settings.loaderImagePath}).appendTo(f);d.appendTo("body")},onProgress:function(b){1>c("#dropster-window").length&&this.createWindow(!0);c(".dropster-window-header").html(b)}};c.fn.dropster=function(b){return this.each(function(){c(this).data("plugin_dropster")||c(this).data("plugin_dropster",new h(this,b))})}})(jQuery);
